# Load the libraries
library(readxl)
library(dplyr)
library(streamgraph)

Sys.setenv(TZ="US/Central")

# Show the sheets in this .xlsx file
excel_sheets("./Data/2018_08-14_NUCATS_Altmetric_Data_For_R.xlsx")

# Just print out sheet 1
NUCATS <- read_excel("./Data/2018_08-14_NUCATS_Altmetric_Data_For_R.xlsx", sheet = "Data For R ")

# Change the first column name from 'Row Labels' to 'Year'
colnames(NUCATS)[1] <- "Year"

# We want to get rid of the two rows with the dates '1900' and '1970'
NUCATS[NUCATS$Year %in% c(1900,1970), ]

# Actually get rid of them, as well as 2018 since the year is still in progress (gives a nice upswing ending with 2017)
NUCATS <- NUCATS[! NUCATS$Year %in% c(1900,1970, 2018), ]

# Create a new column with log(Count) to make the graph behave better
NUCATS_log <- NUCATS %>% mutate(log_count = round(log10(Count), digits = 2))

# Replace '-Inf' values from log10() function about with 0
NUCATS_log$log_count[which(!is.finite(NUCATS_log$log_count))] <- 0

# Create the streamgraph
streamgraph(NUCATS_log, Category, log_count, Year, offset="silhouette", interpolate = "cardinal", interactive = TRUE) %>%
  sg_axis_x(10, tick_units = "Year", tick_format="%Y") %>% # using 'scale = Year' in the streamgraph call cause errors in formatting the x axis
  sg_axis_y(0) %>%
  sg_legend(show=TRUE, label="Metric: ") %>%
  sg_annotate(label="Sum of Number of Mendeley readers", x=2013, y=3.93, color = "black", size = 12)

# References:
# https://rud.is/b/2015/03/12/streamgraph-htmlwidget-version-0-7-released-adds-support-for-markers-annotations/
# https://github.com/hrbrmstr/streamgraph

# Nice tool for extracting a .svg file from the HTML/JS generated by the streamgraph function
# https://nytimes.github.io/svg-crowbar/
